#! /bin/sh

name=test
# version=76810d90fd877b7b5908eede2fe83af5be53c4a5
# source_method=tarball
# tarball_url="https://github.com/managarm/mlibc/archive/${version}.tar.gz"
# tarball_sha512="442449e6e3ac4ad6aaff4e79f447af43a175c7edc3465dcbc8b74abc51022a8d753f502e2ca940be282275d7f91947c9d49b22056b5ab17982e07bef2537f33f"

hostdeps="gcc pkg-config"
# deps="core-libs"



configure() {
    # cp -r /base_dir/mlibc-willowos/sysdeps "${source_dir}/sysdeps/willowos"
    # cp -r /base_dir/mlibc-willowos/abi "${source_dir}/abis/willowos"
    # mkdir -p "${source_dir}/sysdeps/willowos/include/abi-bits"
    # cp -r /base_dir/mlibc-willowos/abi/* "${source_dir}/sysdeps/willowos/include/abi-bits/"

    # mkdir -p "${source_dir}/sysdeps/willowos"
    # cp -r /base_dir/mlibc-sysdeps/willowos "${source_dir}/sysdeps/"
    # cp -r /base_dir/mlibc-sysdeps/willowos/abi "${source_dir}/abis/willowos"
    # mkdir -p "${source_dir}/sysdeps/willowos/include/abi-bits"
    # cp -r /base_dir/mlibc-sysdeps/willowos/abi/* "${source_dir}/sysdeps/willowos/include/abi-bits/"

    echo \n\nHIHIHIHI\n\n

    # mkdir -p "${source_dir}/src"
    # cp -rp /base_dir/src/. "${source_dir}/src/."
    # cp -r /base_dir/src/test.c "${source_dir}/src/test.c"
    # cp -r /base_dir/src/Makefile "${source_dir}/src/Makefile"
}

build() {
    echo ${source_dir}
    cp -rp /base_dir/src "${source_dir}/src"

    make \
        CC=${OS_TRIPLET}-gcc \
        CFLAGS="$TARGET_CFLAGS -std=c99" \
        LDFLAGS="$TARGET_LDFLAGS" \
        -j${parallelism}
}

package() {
    cp -r "${source_dir}/src/test" "${dest_dir}${prefix}"/bin
}



# #! /bin/sh

# name=test
# skip_pkg_check=yes
# revision=51
# # from_source=mlibc
# hostdeps="gcc pkg-config"
# deps="core-libs"

# build() {
#     cp -rp "${source_dir}"/. ./

#     make \
#         CC=${OS_TRIPLET}-gcc \
#         CFLAGS="$TARGET_CFLAGS -std=c99" \
#         LDFLAGS="$TARGET_LDFLAGS" \
#         -j${parallelism}
# }



# package() {
#     DESTDIR="${dest_dir}" meson install --no-rebuild
# }



# #!/bin/sh
# name=mlibc
# version=76810d90fd877b7b5908eede2fe83af5be53c4a5
# source_method=tarball
# tarball_url="https://github.com/managarm/mlibc/archive/${version}.tar.gz"
# tarball_sha512="442449e6e3ac4ad6aaff4e79f447af43a175c7edc3465dcbc8b74abc51022a8d753f502e2ca940be282275d7f91947c9d49b22056b5ab17982e07bef2537f33f"

# prepare() {
#     # cp -r /base_dir/mlibc-willowos/sysdeps "${source_dir}/sysdeps/willowos"
#     # cp -r /base_dir/mlibc-willowos/abi "${source_dir}/abis/willowos"
#     # mkdir -p "${source_dir}/sysdeps/willowos/include/abi-bits"
#     # cp -r /base_dir/mlibc-willowos/abi/* "${source_dir}/sysdeps/willowos/include/abi-bits/"

#     mkdir -p "${source_dir}/sysdeps/willowos"
#     cp -r /base_dir/mlibc-sysdeps/willowos "${source_dir}/sysdeps/"
#     # cp -r /base_dir/mlibc-sysdeps/willowos/abi "${source_dir}/abis/willowos"
#     # mkdir -p "${source_dir}/sysdeps/willowos/include/abi-bits"
#     # cp -r /base_dir/mlibc-sysdeps/willowos/abi/* "${source_dir}/sysdeps/willowos/include/abi-bits/"
# }