#! /bin/sh

name=util-willowos
skip_pkg_check=yes
version=0.0git
revision=1
source_dir="util-willowos"
hostdeps="gcc v"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

    make -j1 \
        PROD="$PROD" \
        CC=${OS_TRIPLET}-gcc \
        VFLAGS="-os willowos -gc none" \
        CFLAGS="$TARGET_CFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS"
}

package() {
    make install PREFIX="${prefix}" DESTDIR="${dest_dir}"

    post_package_strip
}
